### ISSUE TITLE
Getting unexpected keyword argument error in script.py

### ISSUE THREAD

**Issue by maociao** [wawawario2/long_term_memory#11]
Trying the extension for the first time and getting the following error after activating the extension and entering a prompt.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1017, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 849, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 453, in async_iteration
    return next(iterator)
  File "/workspace/text-generation-webui/modules/chat.py", line 177, in cai_chatbot_wrapper
    for _history in chatbot_wrapper(text, max_new_tokens, do_sample, temperature, top_p, typical_p, repetition_penalty, encoder_repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, seed, name1, name2, context, check, chat_prompt_size, chat_generation_attempts):
  File "/workspace/text-generation-webui/modules/chat.py", line 113, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, max_new_tokens, name1, name2, context, chat_prompt_size)
  File "/workspace/text-generation-webui/extensions/long_term_memory/script.py", line 255, in custom_generate_chat_prompt
    (prompt, prompt_rows) = generate_chat_prompt(
TypeError: generate_chat_prompt() got an unexpected keyword argument 'also_return_rows'

**Comment by maociao** [comment]
Nevermind.  I resolved this error by pulling latest from oobabooga.  Now i have a different error "TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'" but I don't know if it is LTM related or not.

**Comment by luckyycode** [comment]
> Nevermind. I resolved this error by pulling latest from oobabooga. Now i have a different error "TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'" but I don't know if it is LTM related or not.

sorry for bumping this one so soon, but seems like LTM is related because otherwise text-generation-webui works

**Comment by digiwombat** [comment]
Confirming the `end_of_turn` error. Latest webui pull and latest LTM pull errors on generate. Suggest reopening the ticket or making a new one for this.

Full Traceback (trimmed the folder paths for readability):
```
Traceback (most recent call last):
  File "\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "\text-generation-webui\modules\chat.py", line 206, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "\text-generation-webui\modules\chat.py", line 134, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'
```

Happens on both WSL2 and Windows native.
