### ISSUE TITLE
custom_generate_chat_prompt() takes 2 positional arguments but 6 were given

### ISSUE THREAD

**Issue by Video-Nomad** [wawawario2/long_term_memory#26]
Hi! With the latest update for oobabooga there seems to be an issue:

```
Traceback (most recent call last):
  File "D:\AI\UI\oobabooga\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\UI\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "D:\AI\UI\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\UI\oobabooga\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\UI\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI\UI\oobabooga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AI\UI\oobabooga\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "D:\AI\UI\oobabooga\text-generation-webui\modules\chat.py", line 224, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, generate_state, name1, name2, context, mode, end_of_turn):
  File "D:\AI\UI\oobabooga\text-generation-webui\modules\chat.py", line 146, in chatbot_wrapper
    prompt = custom_generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
TypeError: custom_generate_chat_prompt() takes 2 positional arguments but 6 were given
```

The error is shown with the LTM extension enabled when you try to write anything in the chat box and press Generate.

**Comment by Video-Nomad** [comment]
I'm sorry for the false report. There was an error on my end during the installation.
